{% set name = "lsdtopotools" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LSDtopotools/LSDTopoTools2/archive/v{{ version }}.tar.gz
  sha256: 2e8f9fb281d60335f4b69111a16979c0ea3f69935529ac4f00e9d38ddbfb6373

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - fftw
    - pcl
  run:
    - fftw
    - pcl

about:
  home: https://github.com/LSDtopotools/LSDTopoTools2
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: LSDTopoTools is a software package for analysing topography
  description: |
    LSDTopoTools is a software package for analysing topography. Applications
    of these analyses span hydrology, geomorphology, soil science, ecology,
    and cognate fields. The software began within the Land Surface Dynamics
    group at the University of Edinburgh, and now has developers and users
    around the world.
  doc_url: https://lsdtopotools.github.io/LSDTT_documentation/
  dev_url: https://github.com/LSDtopotools/LSDTopoTools2

extra:
  recipe-maintainers:
    - mcflugen
