{% set name = "lsdtopotools" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LSDtopotools/LSDTopoTools2/archive/v{{ version }}.tar.gz
  sha256: 7ef347d17460d40063bcf910291542b276f2a84cd8857d9bd79cc6bdc6a4b69d

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - fftw
    - opencv
  run:
    - fftw
    - opencv

about:
  home: https://github.com/LSDtopotools/LSDTopoTools2
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: LSDTopoTools is a software package for analysing topography
  description: |
    LSDTopoTools is a software package for analysing topography. Applications
    of these analyses span hydrology, geomorphology, soil science, ecology,
    and cognate fields. The software began within the Land Surface Dynamics
    group at the University of Edinburgh, and now has developers and users
    around the world.
  doc_url: https://lsdtopotools.github.io/LSDTT_documentation/
  dev_url: https://github.com/LSDtopotools/LSDTopoTools2

extra:
  recipe-maintainers:
    - mcflugen
    - simon-m-mudd
